"""Precompute scenario runs and parameter sweeps for the static web demo.

The demo is a zero-backend artifact: this module runs the engine over every
shipped scenario plus dense parameter grids (tariff rate, Grasberg severity,
restart yes/no) and writes `web/data.js`. The page's "sliders" snap to grid
points — all interactivity, no server, deployable on GitHub Pages for $0.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .balance import BASELINE, run
from .ledger import load_assumptions, load_ledger
from .scenario import SCENARIO_DIR, load_scenario
from .shocks import MineOutage, MineRestart, Scenario, SmelterClosure, Tariff

YEARS = range(2024, 2031)

TARIFF_RATES = [0, 5, 10, 15, 20, 25, 35, 50]
GRASBERG_SEVERITIES = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

CATALYSTS = [
    {
        "name": "US Commerce report: refined-copper tariffs",
        "date": "2026-06-30",
        "detail": "Section 232 — refined cathode currently exempt; this report decides",
    },
    {
        "name": "Panama: Cobre Panamá full-restart decision",
        "date": "2026-06-30",
        "detail": "expected June 2026; stockpile processing (~120kt) already approved",
        "approx": True,
    },
]


def _world_2026_events() -> list:
    return list(load_scenario(SCENARIO_DIR / "world-2026.yaml").events)


def _grasberg_scenario(severity_2026: float) -> Scenario:
    events = [MineOutage(mine="Grasberg", start_year=2025, end_year=2025, severity=0.2)]
    if severity_2026 > 0:
        events.append(
            MineOutage(mine="Grasberg", start_year=2026, end_year=2026, severity=severity_2026)
        )
        if severity_2026 / 2 > 0:
            events.append(
                MineOutage(
                    mine="Grasberg", start_year=2027, end_year=2027, severity=severity_2026 / 2
                )
            )
    return Scenario(name=f"grasberg-sev-{severity_2026:.1f}", events=events)


def build_payload() -> dict:
    ledger = load_ledger()
    assumptions = load_assumptions()

    def rows(scenario: Scenario) -> list[dict]:
        return [asdict(r) for r in run(ledger, assumptions, scenario, YEARS).rows]

    baseline_rows = rows(BASELINE)

    scenarios = {}
    for path in sorted(SCENARIO_DIR.glob("*.yaml")):
        scenario = load_scenario(path)
        scenarios[scenario.name] = {
            "description": scenario.description,
            "rows": rows(scenario),
        }

    tariff_runs = {
        str(rate): rows(
            Scenario(
                name=f"tariff-{rate}",
                events=[Tariff(rate_pct=rate, start_year=2026)] if rate else [],
            )
        )
        for rate in TARIFF_RATES
    }

    grasberg_runs = {
        f"{sev:.1f}": rows(_grasberg_scenario(sev)) for sev in GRASBERG_SEVERITIES
    }

    world = _world_2026_events()
    restart = MineRestart(mine="Cobre Panama", ramp={2026: 120, 2027: 280})
    decision_runs = {
        "no": rows(Scenario(name="world-2026", events=world)),
        "yes": rows(Scenario(name="world-2026+restart", events=world + [restart])),
    }

    year0 = YEARS[0]
    tracked = sum(m.production(year0) for m in ledger.mines)
    coverage = tracked / assumptions.world.mine_supply(year0)

    return {
        "meta": {
            "years": list(YEARS),
            "catalysts": CATALYSTS,
            "tracked_mines": len(ledger.mines),
            "coverage_pct": round(100 * coverage),
        },
        "baseline": baseline_rows,
        "scenarios": scenarios,
        "labs": {
            "tariff": {"values": TARIFF_RATES, "runs": tariff_runs},
            "grasberg": {"values": GRASBERG_SEVERITIES, "runs": grasberg_runs},
            "decision": {"runs": decision_runs},
        },
        "mines": [
            {
                "name": m.name,
                "country": m.country,
                "owner": m.owner,
                "status": m.status.value,
                "capacity_kt": m.capacity_kt,
                "production_2026_kt": round(
                    m.production(2026, assumptions.world.tracked_utilization)
                ),
                "basis": m.basis.value,
                "lat": m.lat,
                "lon": m.lon,
                "notes": m.notes or "",
            }
            for m in sorted(ledger.mines, key=lambda m: -m.capacity_kt)
        ],
    }


def export_web(out_path: Path) -> Path:
    payload = build_payload()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "// generated by `opencopper export-web` — do not edit\n"
        f"window.OPENCOPPER_DATA = {json.dumps(payload)};\n"
    )
    return out_path
