"""Thesis ledger: every call the system makes, marked to market daily.

Two populations share one scorecard:

- **Registered theses** (`data/theses.yaml`) — the machine-readable twin of
  PREDICTIONS.md. Markable metrics grade themselves off keyless series;
  `external` ones stay open until a hand-added `resolution:` block cites a
  source. Past-deadline externals show as NEEDS-RES, loudly.
- **Auto theses** (`data/theses-auto.json`) — generated by the news pipeline:
  each distinct rule-matched supply event becomes "price rises ≥X% vs entry
  within H months", with the entry price snapshotted at creation. These test
  the news→simulation loop's actual predictive value, which is the question
  a quant asks of any signal: not "is the mechanism plausible" but "what
  happened next, every time it fired".

Statuses: OPEN (deadline ahead), HIT, MISS, NEEDS-RES (external, past
deadline, unresolved). Analytics: hit rate over resolved, Brier score where
the model attached a probability, and the open auto-theses' current
paper move. Scoring is the product; nothing here sizes or recommends.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import date, datetime, timezone
from pathlib import Path

import yaml

REGISTRY_PATH = Path("data/theses.yaml")
AUTO_PATH = Path("data/theses-auto.json")


@dataclass
class Marked:
    id: str
    created: str
    commodity: str
    claim: str
    kind: str          # registered | auto
    metric: str
    status: str        # open | hit | miss | needs-res
    reading: str       # human-readable current state
    deadline: str
    resolved_on: str | None = None
    prob: float | None = None
    move_pct: float | None = None  # current move vs entry (auto theses)


def _months(commodity: str) -> list[tuple[str, float]]:
    from .history import load_price_history

    h = load_price_history(commodity)
    return h.months if h else []


def _add_months(d: date, n: int) -> date:
    y, m = d.year + (d.month - 1 + n) // 12, (d.month - 1 + n) % 12 + 1
    return date(y, m, 1)


def _today() -> date:
    return datetime.now(timezone.utc).date()


def load_registry(path: Path = REGISTRY_PATH) -> list[dict]:
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text())["theses"]


def load_auto(path: Path = AUTO_PATH) -> list[dict]:
    if not path.exists():
        return []
    return json.loads(path.read_text())


def mark_registered(t: dict, today: date | None = None) -> Marked:
    today = today or _today()
    deadline = date.fromisoformat(t["resolves_by"])
    base = dict(id=t["id"], created=t["created"], commodity=t["commodity"],
                claim=t["claim"], kind="registered", metric=t["metric"],
                deadline=t["resolves_by"], prob=t.get("prob"))

    if t.get("resolution"):  # manual resolution wins for any metric
        r = t["resolution"]
        return Marked(**base, status=r["outcome"], resolved_on=r["date"],
                      reading=r.get("note", r["outcome"]))

    if t["metric"] == "annual_avg_band":
        rows = [v for d, v in _months(t["commodity"]) if d.startswith(str(t["year"]))]
        if not rows:
            return Marked(**base, status="open", reading="no readings yet")
        avg = sum(rows) / len(rows)
        inside = t["lo"] <= avg <= t["hi"]
        if len(rows) >= 12:  # the year has fully printed
            return Marked(**base, status="hit" if inside else "miss",
                          resolved_on=f"{t['year']}-12-31",
                          reading=f"{t['year']} avg {avg:,.0f} vs [{t['lo']:,}-{t['hi']:,}]")
        return Marked(**base, status="open",
                      reading=f"YTD avg {avg:,.0f} ({len(rows)} mo) vs [{t['lo']:,}-{t['hi']:,}]"
                              f"{' — inside' if inside else ' — OUTSIDE'}")

    # external: trackable only by hand
    if today > deadline:
        return Marked(**base, status="needs-res",
                      reading="past deadline — add a resolution: block with a source")
    return Marked(**base, status="open", reading="awaiting external resolution")


def mark_auto(t: dict, today: date | None = None) -> Marked:
    today = today or _today()
    created = date.fromisoformat(t["created"])
    deadline = _add_months(created, t["horizon_months"])
    base = dict(id=t["id"], created=t["created"], commodity=t["commodity"],
                claim=t["claim"], kind="auto", metric="price_change",
                deadline=deadline.isoformat())

    months = _months(t["commodity"])
    after = [(d, v) for d, v in months if d > t["entry_date"]]
    entry = t["entry_price"]
    threshold = entry * (1 + t["min_move_pct"] / 100)

    # first monthly print at/over the threshold resolves the thesis
    for d, v in after:
        if date.fromisoformat(d) > deadline:
            break
        if v >= threshold:
            return Marked(**base, status="hit", resolved_on=d,
                          move_pct=round(100 * (v / entry - 1), 1),
                          reading=f"{v:,.0f} ≥ {threshold:,.0f} on {d[:7]}")
    current = after[-1] if after else (t["entry_date"], entry)
    move = round(100 * (current[1] / entry - 1), 1)
    if today > deadline:
        return Marked(**base, status="miss", resolved_on=deadline.isoformat(),
                      move_pct=move,
                      reading=f"never printed ≥ {threshold:,.0f}; ended {move:+.1f}%")
    return Marked(**base, status="open", move_pct=move,
                  reading=f"now {current[1]:,.0f} ({move:+.1f}% vs entry {entry:,.0f})")


def mark_all(today: date | None = None) -> list[Marked]:
    out = [mark_registered(t, today) for t in load_registry()]
    out += [mark_auto(t, today) for t in load_auto()]
    return out


def analytics(marked: list[Marked]) -> dict:
    by = lambda s: [m for m in marked if m.status == s]
    resolved = by("hit") + by("miss")
    briers = [(m.prob - (1.0 if m.status == "hit" else 0.0)) ** 2
              for m in resolved if m.prob is not None]
    open_auto = [m for m in marked if m.kind == "auto" and m.status == "open"
                 and m.move_pct is not None]
    return {
        "n": len(marked),
        "open": len(by("open")),
        "hit": len(by("hit")),
        "miss": len(by("miss")),
        "needs_res": len(by("needs-res")),
        "hit_rate": round(len(by("hit")) / len(resolved), 3) if resolved else None,
        "brier": round(sum(briers) / len(briers), 3) if briers else None,
        "open_auto_avg_move_pct": round(sum(m.move_pct for m in open_auto) / len(open_auto), 1)
                                  if open_auto else None,
    }


def render_theses(marked: list[Marked]) -> str:
    from .signals import DISCLAIMER

    a = analytics(marked)
    lines = ["THESIS SCORECARD — every call, marked to market",
             f"{'id':<30}{'made':>11}{'deadline':>11}{'status':>10}  reading",
             "-" * 96]
    order = {"hit": 0, "miss": 1, "needs-res": 2, "open": 3}
    for m in sorted(marked, key=lambda m: (order[m.status], m.created)):
        lines.append(f"{m.id[:29]:<30}{m.created:>11}{m.deadline:>11}"
                     f"{m.status.upper():>10}  {m.reading}")
    lines += ["-" * 96,
              f"{a['n']} theses: {a['hit']} hit / {a['miss']} miss / {a['open']} open"
              f" / {a['needs_res']} need resolution"
              + (f" · hit rate {a['hit_rate']:.0%}" if a['hit_rate'] is not None else "")
              + (f" · Brier {a['brier']}" if a['brier'] is not None else "")
              + (f" · open auto theses avg move {a['open_auto_avg_move_pct']:+.1f}%"
                 if a['open_auto_avg_move_pct'] is not None else ""),
              "",
              "Registered theses mirror PREDICTIONS.md; auto theses are generated by the",
              "news pipeline (entry snapshotted at creation, first monthly print ≥ threshold",
              "resolves). Misses stay forever. " + DISCLAIMER]
    return "\n".join(lines)


def theses_json(marked: list[Marked]) -> str:
    return json.dumps({"analytics": analytics(marked),
                       "theses": [asdict(m) for m in marked]}, indent=1)


# ------------------------------------------------------- auto-generation


def generate_auto_theses(hits: list[dict], today: str,
                         auto_path: Path = AUTO_PATH,
                         min_move_pct: float = 5.0,
                         horizon_months: int = 6) -> list[dict]:
    """Turn each distinct rule-matched supply event into a trackable thesis.
    One per (commodity, country, severity, month) — corroborating headlines
    don't multiply theses. Commodities without a keyless monthly series are
    skipped (untrackable claims aren't theses, they're prose). Returns the
    newly added entries."""
    existing = load_auto(auto_path)
    seen = {t["id"] for t in existing}
    added = []
    for h in hits:
        if h["severity"] <= 0:
            continue  # supply additions ease markets; no squeeze thesis
        ident = (f"auto-{today[:7]}-{h['commodity']}-"
                 f"{h['country'].lower().replace(' ', '-').replace('(', '').replace(')', '')}")
        if ident in seen:
            continue
        months = _months(h["commodity"])
        if not months:
            continue
        entry_date, entry_price = months[-1]
        added.append({
            "id": ident,
            "created": today,
            "commodity": h["commodity"],
            "country": h["country"],
            "severity": h["severity"],
            "claim": (f"news-implied supply event ({h['country']} {h['commodity']} "
                      f"-{h['severity']:.0%} prior): price prints ≥+{min_move_pct:.0f}% "
                      f"vs entry within {horizon_months}m"),
            "metric": "price_change",
            "min_move_pct": min_move_pct,
            "horizon_months": horizon_months,
            "entry_date": entry_date,
            "entry_price": entry_price,
            "basis": h["headline"][:140],
        })
        seen.add(ident)
    if added:
        auto_path.parent.mkdir(parents=True, exist_ok=True)
        auto_path.write_text(json.dumps(existing + added, indent=1))
    return added
